
// ==========================================
// 1. BASE DE DATOS MASIVA (Completa y Organizada)
// ==========================================
const emojiData = [
    // --- CARAS (emociones) ---
    { char: "😀", tags: "cara feliz sonrisa alegre", cat: "caras" },
    { char: "😃", tags: "cara feliz ojos abiertos", cat: "caras" },
    { char: "😄", tags: "cara risa ojos cerrados", cat: "caras" },
    { char: "😁", tags: "cara radiante dientes", cat: "caras" },
    { char: "😆", tags: "cara carcajada", cat: "caras" },
    { char: "😅", tags: "cara sudor risa", cat: "caras" },
    { char: "😂", tags: "risa lagrimas joy", cat: "caras" },
    { char: "🤣", tags: "risa suelo rotfl", cat: "caras" },
    { char: "😊", tags: "sonrisa mejillas", cat: "caras" },
    { char: "😇", tags: "angel inocente", cat: "caras" },
    { char: "🥰", tags: "amor corazones enamorado", cat: "caras" },
    { char: "😍", tags: "ojos corazon amor", cat: "caras" },
    { char: "🤩", tags: "estrellas ojos", cat: "caras" },
    { char: "😘", tags: "beso corazon", cat: "caras" },
    { char: "😋", tags: "lengua comida delicioso", cat: "caras" },
    { char: "🤑", tags: "dinero lengua ojos", cat: "caras" },
    { char: "🤔", tags: "pensar duda", cat: "caras" },
    { char: "🤫", tags: "silencio shh", cat: "caras" },
    { char: "😎", tags: "gafas sol genial cool", cat: "caras" },
    { char: "🥳", tags: "fiesta celebracion", cat: "caras" },
    { char: "🤯", tags: "cabeza explosion mente", cat: "caras" },
    { char: "🥺", tags: "por favor ojitos", cat: "caras" },
    { char: "😱", tags: "grito susto wow", cat: "caras" },
    { char: "😭", tags: "llanto fuerte lloro", cat: "caras" },
    { char: "😡", tags: "rabia rojo enfadado", cat: "caras" },
    { char: "💀", tags: "calavera muerte", cat: "caras" },
    { char: "🧠", tags: "cerebro mente inteligencia", cat: "caras" },
    { char: "😀", tags: "cara feliz sonrisa alegre", cat: "caras" },
    { char: "😃", tags: "cara feliz ojos abiertos", cat: "caras" },
    { char: "😄", tags: "cara risa ojos cerrados", cat: "caras" },
    { char: "😁", tags: "cara radiante dientes", cat: "caras" },
    { char: "😆", tags: "cara carcajada", cat: "caras" },
    { char: "😅", tags: "cara sudor risa", cat: "caras" },
    { char: "🤣", tags: "risa suelo rotfl", cat: "caras" },
    { char: "😂", tags: "risa lagrimas joy", cat: "caras" },
    { char: "🙂", tags: "cara sonrisa leve", cat: "caras" },
    { char: "😉", tags: "guiño ojo", cat: "caras" },
    { char: "😊", tags: "sonrisa mejillas", cat: "caras" },
    { char: "😇", tags: "angel inocente", cat: "caras" },
    { char: "🥰", tags: "amor corazones enamorado", cat: "caras" },
    { char: "😍", tags: "ojos corazon amor", cat: "caras" },
    { char: "🤩", tags: "estrellas ojos", cat: "caras" },
    { char: "😘", tags: "beso corazon", cat: "caras" },
    { char: "😋", tags: "lengua comida delicioso", cat: "caras" },
    { char: "🤑", tags: "dinero lengua ojos", cat: "caras" },
    { char: "🤔", tags: "pensar duda", cat: "caras" },
    { char: "🤫", tags: "silencio shh", cat: "caras" },
    { char: "😎", tags: "gafas sol genial cool", cat: "caras" },
    { char: "🥳", tags: "fiesta celebracion", cat: "caras" },
    { char: "🤯", tags: "cabeza explosion mente", cat: "caras" },
    { char: "🥺", tags: "por favor ojitos", cat: "caras" },
    { char: "😱", tags: "grito susto wow", cat: "caras" },
    { char: "😭", tags: "llanto fuerte lloro", cat: "caras" },
    { char: "😡", tags: "rabia rojo enfadado", cat: "caras" },
    { char: "💀", tags: "calavera muerte muerto risa", cat: "caras" },
    { char: "🦾", tags: "brazo robot fuerte", cat: "caras" },
    { char: "🧠", tags: "cerebro mente inteligencia", cat: "caras" },

    // --- VENTAS Y NEGOCIOS (ventas) ---
    { char: "💰", tags: "dinero bolsa ventas cash", cat: "ventas" },
    { char: "💵", tags: "billete dolar dinero", cat: "ventas" },
    { char: "💹", tags: "grafica subir mercado", cat: "ventas" },
    { char: "📈", tags: "crecimiento tendencia", cat: "ventas" },
    { char: "🛍️", tags: "compras bolsa tienda shop", cat: "ventas" },
    { char: "🛒", tags: "carrito compra", cat: "ventas" },
    { char: "🏷️", tags: "etiqueta oferta precio", cat: "ventas" },
    { char: "💳", tags: "tarjeta credito pago", cat: "ventas" },
    { char: "💎", tags: "diamante joya premium", cat: "ventas" },
    { char: "🎁", tags: "regalo sorpresa bono", cat: "ventas" },
    { char: "📢", tags: "anuncio megafono atencion", cat: "ventas" },
    { char: "📣", tags: "altavoz noticia", cat: "ventas" },
    { char: "🔔", tags: "campana notificacion", cat: "ventas" },
    { char: "🎯", tags: "objetivo meta blanco", cat: "ventas" },
    { char: "🏆", tags: "trofeo ganador premio", cat: "ventas" },
    { char: "🤝", tags: "trato acuerdo manos", cat: "ventas" },
    { char: "💡", tags: "idea luz brillante", cat: "ventas" },
    { char: "💻", tags: "laptop pc trabajo", cat: "ventas" },
    { char: "📱", tags: "movil celular whatsapp contacto", cat: "ventas" },
    { char: "📦", tags: "paquete envio entrega", cat: "ventas" },
    { char: "✅", tags: "check verificado ok confirmado", cat: "ventas" },
    { char: "⭐", tags: "estrella rating favorito", cat: "ventas" },
    { char: "📍", tags: "ubicacion mapa lugar tienda", cat: "ventas" },
        { char: "💰", tags: "dinero bolsa ventas cash", cat: "ventas" },
    { char: "💵", tags: "billete dolar dinero", cat: "ventas" },
    { char: "💹", tags: "grafica subir mercado", cat: "ventas" },
    { char: "📈", tags: "crecimiento tendencia", cat: "ventas" },
    { char: "🛍️", tags: "compras bolsa tienda shop", cat: "ventas" },
    { char: "🛒", tags: "carrito compra", cat: "ventas" },
    { char: "🏷️", tags: "etiqueta oferta precio", cat: "ventas" },
    { char: "💳", tags: "tarjeta credito pago", cat: "ventas" },
    { char: "💎", tags: "diamante joya premium", cat: "ventas" },
    { char: "🎁", tags: "regalo sorpresa bono", cat: "ventas" },
    { char: "📢", tags: "anuncio megafono atencion", cat: "ventas" },
    { char: "📣", tags: "altavoz noticia", cat: "ventas" },
    { char: "🔔", tags: "campana notificacion", cat: "ventas" },
    { char: "🎯", tags: "objetivo meta blanco", cat: "ventas" },
    { char: "🏆", tags: "trofeo ganador premio", cat: "ventas" },
    { char: "🤝", tags: "trato acuerdo manos", cat: "ventas" },
    { char: "💡", tags: "idea luz brillante", cat: "ventas" },
    { char: "💻", tags: "laptop pc trabajo", cat: "ventas" },
    { char: "📱", tags: "movil celular whatsapp contacto", cat: "ventas" },
    { char: "📦", tags: "paquete envio entrega", cat: "ventas" },
    { char: "🚚", tags: "camion transporte", cat: "ventas" },
    { char: "✅", tags: "check verificado ok confirmado", cat: "ventas" },
    { char: "⭐", tags: "estrella rating favorito", cat: "ventas" },
    { char: "🔜", tags: "proximamente pronto", cat: "ventas" },
    { char: "🆕", tags: "nuevo new", cat: "ventas" },
    { char: "📍", tags: "ubicacion mapa lugar tienda", cat: "ventas" },
    { char: "⚠️", tags: "atencion advertencia cuidado", cat: "ventas" },
    { char: "🔗", tags: "link enlace conexion", cat: "ventas" },
    { char: "📉", tags: "bajada perdida", cat: "ventas" },
    { char: "🏢", tags: "edificio empresa oficina", cat: "ventas" },

    // --- TENDENCIAS (fuego) ---
    { char: "🔥", tags: "fuego popular tendencia hot", cat: "fuego" },
    { char: "✨", tags: "gemini brillos magia estrellas sparkle", cat: "fuego" },
    { char: "🚀", tags: "cohete despegar crecer marketing", cat: "fuego" },
    { char: "💯", tags: "cien perfecto excelente", cat: "fuego" },
    { char: "💥", tags: "boom explosion impacto", cat: "fuego" },
    { char: "⚡", tags: "rayo trueno energia rapido", cat: "fuego" },
    { char: "🎉", tags: "celebracion fiesta", cat: "fuego" },
    { char: "🎊", tags: "confeti", cat: "fuego" },
    { char: "👇", tags: "abajo flecha mirar", cat: "fuego" },
    { char: "🤖", tags: "robot bot ia", cat: "fuego" },
    { char: "🔥", tags: "fuego popular tendencia hot", cat: "fuego" },
    { char: "✨", tags: "brillos magia estrellas sparkle", cat: "fuego" },
    { char: "🚀", tags: "cohete despegar crecer marketing", cat: "fuego" },
    { char: "💯", tags: "cien perfecto excelente", cat: "fuego" },
    { char: "💥", tags: "boom explosion impacto", cat: "fuego" },
    { char: "⚡", tags: "rayo trueno energia rapido", cat: "fuego" },
    { char: "🌈", tags: "arcoiris color", cat: "fuego" },
    { char: "👑", tags: "corona rey reina", cat: "fuego" },
    { char: "🎉", tags: "celebracion fiesta", cat: "fuego" },
    { char: "🎊", tags: "confeti", cat: "fuego" },
    { char: "🌊", tags: "ola mar agua", cat: "fuego" },
    { char: "☀️", tags: "sol verano luz", cat: "fuego" },
    { char: "🎮", tags: "ps play mando consola juego", cat: "fuego" },
    { char: "🤖", tags: "robocop gemini robot bot ia", cat: "fuego" },
    { char: "💎", tags: "diamante joya premium", cat: "fuego" },
    { char: "👇", tags: "abajo flecha mirar", cat: "fuego" },

    // --- ANIMALES ---
    { char: "🐶", tags: "perro animal mascota", cat: "animales" },
    { char: "🐱", tags: "gato animal miau", cat: "animales" },
    { char: "🦁", tags: "leon rey selva", cat: "animales" },
    { char: "🐯", tags: "tigre animal", cat: "animales" },
    { char: "🦒", tags: "jirafa alto", cat: "animales" },
    { char: "🐘", tags: "elefante grande", cat: "animales" },
    { char: "🦄", tags: "unicornio magia", cat: "animales" },
    { char: "🐾", tags: "huellas perro", cat: "animales" },
    { char: "🐶", tags: "dog perro animal mascota", cat: "animales" },
    { char: "🐱", tags: "gato animal miau", cat: "animales" },
    { char: "🦁", tags: "leon rey selva", cat: "animales" },
    { char: "🐯", tags: "tigre animal", cat: "animales" },
    { char: "🦒", tags: "jirafa alto", cat: "animales" },
    { char: "🐘", tags: "elefante grande", cat: "animales" },
    { char: "🐭", tags: "raton queso", cat: "animales" },
    { char: "🐹", tags: "hamster mascota", cat: "animales" },
    { char: "🐰", tags: "conejo pascua", cat: "animales" },
    { char: "🦊", tags: "zorro astuto", cat: "animales" },
    { char: "🐻", tags: "oso peluche", cat: "animales" },
    { char: "🐼", tags: "panda china", cat: "animales" },
    { char: "🐨", tags: "koala australia", cat: "animales" },
    { char: "🐷", tags: "cerdo puerco", cat: "animales" },
    { char: "🐸", tags: "rana sapo", cat: "animales" },
    { char: "🐵", tags: "mono simio", cat: "animales" },
    { char: "🐔", tags: "pollo gallina", cat: "animales" },
    { char: "🐧", tags: "pinguino frio", cat: "animales" },
    { char: "🐦", tags: "pajaro ave", cat: "animales" },
    { char: "🐤", tags: "pollito amarillo", cat: "animales" },
    { char: "🦆", tags: "pato", cat: "animales" },
    { char: "🦅", tags: "aguila usa", cat: "animales" },
    { char: "🦉", tags: "buho noche", cat: "animales" },
    { char: "🦇", tags: "murcielago batman", cat: "animales" },
    { char: "🐺", tags: "lobo luna", cat: "animales" },
    { char: "🐗", tags: "jabali", cat: "animales" },
    { char: "🐴", tags: "caballo", cat: "animales" },
    { char: "🦄", tags: "unicornio magia", cat: "animales" },
    { char: "🐝", tags: "abeja miel", cat: "animales" },
    { char: "🐛", tags: "gusano insecto", cat: "animales" },
    { char: "🦋", tags: "mariposa", cat: "animales" },
    { char: "🐌", tags: "caracol lento", cat: "animales" },
    { char: "🐞", tags: "mariquita", cat: "animales" },
    { char: "🐜", tags: "hormiga", cat: "animales" },
    { char: "🦟", tags: "mosquito", cat: "animales" },
    { char: "🦗", tags: "grillo", cat: "animales" },
    { char: "🕷️", tags: "araña", cat: "animales" },
    { char: "🦂", tags: "alacran", cat: "animales" },
    { char: "🐢", tags: "tortuga", cat: "animales" },
    { char: "🐍", tags: "serpiente", cat: "animales" },
    { char: "🦎", tags: "lagartija", cat: "animales" },
    { char: "🦖", tags: "dinosaurio t-rex", cat: "animales" },
    { char: "🐙", tags: "pulpo", cat: "animales" },
    { char: "🦑", tags: "calamar", cat: "animales" },
    { char: "🦐", tags: "camaron", cat: "animales" },
    { char: "🦀", tags: "cangrejo", cat: "animales" },
    { char: "🐡", tags: "pez globo", cat: "animales" },
    { char: "🐠", tags: "pez tropical", cat: "animales" },
    { char: "🐟", tags: "pez pescado", cat: "animales" },
    { char: "🐬", tags: "delfin", cat: "animales" },
    { char: "🐳", tags: "ballena", cat: "animales" },
    { char: "🐋", tags: "ballena azul", cat: "animales" },
    { char: "🦈", tags: "tiburon jason", cat: "animales" },
    { char: "🐊", tags: "cocodrilo", cat: "animales" },
    { char: "🐅", tags: "tigre", cat: "animales" },
    { char: "🐆", tags: "leopardo", cat: "animales" },
    { char: "🦓", tags: "cebra", cat: "animales" },
    { char: "🦍", tags: "gorila", cat: "animales" },
    { char: "🦧", tags: "orangutan", cat: "animales" },
    { char: "🐘", tags: "elefante", cat: "animales" },
    { char: "🦛", tags: "hipopotamo", cat: "animales" },
    { char: "🦏", tags: "rinoceronte", cat: "animales" },
    { char: "🐪", tags: "camello", cat: "animales" },
    { char: "🐫", tags: "dromedario", cat: "animales" },
    { char: "🦒", tags: "jirafa", cat: "animales" },
    { char: "🦘", tags: "canguro", cat: "animales" },
    { char: "🐃", tags: "bufalo", cat: "animales" },
    { char: "🐂", tags: "buey", cat: "animales" },
    { char: "🐄", tags: "vaca", cat: "animales" },
    { char: "🐎", tags: "caballo", cat: "animales" },
    { char: "🐖", tags: "cerdo", cat: "animales" },
    { char: "🐏", tags: "carnero", cat: "animales" },
    { char: "🐑", tags: "oveja", cat: "animales" },
    { char: "🐐", tags: "cabra", cat: "animales" },
    { char: "🦌", tags: "ciervo", cat: "animales" },
    { char: "🐕", tags: "perro", cat: "animales" },
    { char: "🐩", tags: "caniche", cat: "animales" },
    { char: "🐈", tags: "gato", cat: "animales" },
    { char: "🐓", tags: "gallo", cat: "animales" },
    { char: "🦃", tags: "pavo", cat: "animales" },
    { char: "🕊️", tags: "paloma paz", cat: "animales" },
    { char: "🐇", tags: "conejo", cat: "animales" },
    { char: "🐁", tags: "raton", cat: "animales" },
    { char: "🐀", tags: "rata", cat: "animales" },
    { char: "🐿️", tags: "ardilla", cat: "animales" },
    { char: "🦔", tags: "erizo", cat: "animales" },
    { char: "🐾", tags: "huellas", cat: "animales" },
    { char: "🐉", tags: "dragon", cat: "animales" },
    { char: "🐲", tags: "dragon", cat: "animales" },
    { char: "🌵", tags: "cactus desierto", cat: "animales" },
    { char: "🎄", tags: "navidad arbol", cat: "animales" },
    { char: "🌲", tags: "pino arbol", cat: "animales" },
    { char: "🌳", tags: "arbol", cat: "animales" },
    { char: "🌴", tags: "palmera playa", cat: "animales" },
    { char: "🌱", tags: "planta brote", cat: "animales" },
    { char: "🌿", tags: "hierba", cat: "animales" },
    { char: "☘️", tags: "trebol", cat: "animales" },
    { char: "🍀", tags: "trebol suerte", cat: "animales" },
    { char: "🍃", tags: "hojas viento", cat: "animales" },
    { char: "🍂", tags: "hojas otoño", cat: "animales" },
    { char: "🍁", tags: "maple canada", cat: "animales" },
    { char: "🍄", tags: "hongo mario", cat: "animales" },
    { char: "🐚", tags: "concha mar", cat: "animales" },
    { char: "🌹", tags: "rosa flor amor", cat: "animales" },
    { char: "🥀", tags: "flor marchita", cat: "animales" },
    { char: "🌺", tags: "hibisco", cat: "animales" },
    { char: "🌻", tags: "girasol", cat: "animales" },
    { char: "🌼", tags: "flor blanca", cat: "animales" },
    { char: "🌷", tags: "tulipan", cat: "animales" },
    { char: "🌾", tags: "arroz planta", cat: "animales" },

    // --- COMIDA ---
    { char: "🍎", tags: "manzana fruta roja", cat: "comida" },
    { char: "🍌", tags: "banana platano", cat: "comida" },
    { char: "🍉", tags: "sandia fruta", cat: "comida" },
    { char: "🍓", tags: "fresa fruta", cat: "comida" },
    { char: "🍔", tags: "hamburguesa fast food", cat: "comida" },
    { char: "🍟", tags: "papas fritas", cat: "comida" },
    { char: "🍕", tags: "pizza comida italiana", cat: "comida" },
    { char: "🌮", tags: "taco mexicano", cat: "comida" },
    { char: "🍺", tags: "cerveza jarra", cat: "comida" },
    { char: "🥤", tags: "soda vaso", cat: "comida" },
    { char: "🍎", tags: "manzana fruta roja", cat: "comida" },
    { char: "🍐", tags: "pera fruta", cat: "comida" },
    { char: "🍊", tags: "naranja fruta", cat: "comida" },
    { char: "🍋", tags: "limon acido", cat: "comida" },
    { char: "🍌", tags: "banana platano", cat: "comida" },
    { char: "🍉", tags: "sandia fruta", cat: "comida" },
    { char: "🍇", tags: "uvas vino", cat: "comida" },
    { char: "🍓", tags: "fresa fruta", cat: "comida" },
    { char: "🍈", tags: "melon", cat: "comida" },
    { char: "🍒", tags: "cerezas fruta", cat: "comida" },
    { char: "🍑", tags: "durazno fruta", cat: "comida" },
    { char: "🍍", tags: "piña fruta", cat: "comida" },
    { char: "🥭", tags: "mango fruta", cat: "comida" },
    { char: "🥥", tags: "coco fruta", cat: "comida" },
    { char: "🥝", tags: "kiwi fruta", cat: "comida" },
    { char: "🍅", tags: "tomate verdura", cat: "comida" },
    { char: "🍆", tags: "berenjena verdura", cat: "comida" },
    { char: "🥑", tags: "aguacate palta", cat: "comida" },
    { char: "🥦", tags: "brocoli verdura", cat: "comida" },
    { char: "🥬", tags: "lechuga verdura", cat: "comida" },
    { char: "🥒", tags: "pepino verdura", cat: "comida" },
    { char: "🌽", tags: "maiz choclo", cat: "comida" },
    { char: "🥕", tags: "zanahoria verdura", cat: "comida" },
    { char: "🥔", tags: "papa patata", cat: "comida" },
    { char: "🥨", tags: "pretzel pan", cat: "comida" },
    { char: "🥖", tags: "pan frances", cat: "comida" },
    { char: "🍞", tags: "pan molde", cat: "comida" },
    { char: "🥐", tags: "cruasan pan", cat: "comida" },
    { char: "🥯", tags: "bagel pan", cat: "comida" },
    { char: "🥞", tags: "panqueque desayuno", cat: "comida" },
    { char: "🧇", tags: "waffle desayuno", cat: "comida" },
    { char: "🧀", tags: "queso raton", cat: "comida" },
    { char: "🍖", tags: "carne hueso", cat: "comida" },
    { char: "🍗", tags: "pollo pierna", cat: "comida" },
    { char: "🥩", tags: "carne filete", cat: "comida" },
    { char: " Bacon", char: "🥓", tags: "tocino bacon", cat: "comida" },
    { char: "🍔", tags: "hamburguesa fast food", cat: "comida" },
    { char: "🍟", tags: "papas fritas", cat: "comida" },
    { char: "🍕", tags: "pizza comida italiana", cat: "comida" },
    { char: "🌭", tags: "hot dog perro caliente", cat: "comida" },
    { char: "🥪", tags: "sandwich emparedado", cat: "comida" },
    { char: "🌮", tags: "taco mexicano", cat: "comida" },
    { char: "burrito", char: "🌯", tags: "burrito mexicano", cat: "comida" },
    { char: "🍳", tags: "huevo frito", cat: "comida" },
    { char: "🍲", tags: "sopa comida", cat: "comida" },
    { char: "🥣", tags: "cereal tazon", cat: "comida" },
    { char: "🥗", tags: "ensalada saludable", cat: "comida" },
    { char: "🍿", tags: "palomitas cine", cat: "comida" },
    { char: "🧈", tags: "mantequilla", cat: "comida" },
    { char: "🧂", tags: "sal condimento", cat: "comida" },
    { char: "🥫", tags: "lata comida", cat: "comida" },
    { char: "🍱", tags: "bento japones", cat: "comida" },
    { char: "🍘", tags: "galleta arroz", cat: "comida" },
    { char: "🍙", tags: "onigiri arroz", cat: "comida" },
    { char: "🍚", tags: "arroz blanco", cat: "comida" },
    { char: "🍛", tags: "curry arroz", cat: "comida" },
    { char: "🍜", tags: "ramen fideos", cat: "comida" },
    { char: "🍝", tags: "espagueti fideos", cat: "comida" },
    { char: "🍠", tags: "camote asado", cat: "comida" },
    { char: "🍢", tags: "oden japones", cat: "comida" },
    { char: "🍣", tags: "sushi pescado", cat: "comida" },
    { char: "🍤", tags: "tempura camaron", cat: "comida" },
    { char: "🍥", tags: "naruto pescado", cat: "comida" },
    { char: "🥮", tags: "pastel luna", cat: "comida" },
    { char: "🍡", tags: "dango japones", cat: "comida" },
    { char: "🥟", tags: "gyoza empanada", cat: "comida" },
    { char: "🥠", tags: "galleta fortuna", cat: "comida" },
    { char: "🥡", tags: "comida llevar", cat: "comida" },
    { char: "🍦", tags: "helado cono", cat: "comida" },
    { char: "🍧", tags: "granizado helado", cat: "comida" },
    { char: "🍨", tags: "helado tazon", cat: "comida" },
    { char: "🍩", tags: "dona donut", cat: "comida" },
    { char: "🍪", tags: "galleta cookie", cat: "comida" },
    { char: "🎂", tags: "pastel cumpleaños", cat: "comida" },
    { char: "🍰", tags: "rebanada pastel", cat: "comida" },
    { char: "🧁", tags: "magdalena cupcake", cat: "comida" },
    { char: "🥧", tags: "pie tarta", cat: "comida" },
    { char: "🍫", tags: "chocolate dulce", cat: "comida" },
    { char: "🍬", tags: "caramelo dulce", cat: "comida" },
    { char: "🍭", tags: "paleta dulce", cat: "comida" },
    { char: "🍮", tags: "flan postre", cat: "comida" },
    { char: "🍯", tags: "miel oso", cat: "comida" },
    { char: "🍼", tags: "biberon bebe", cat: "comida" },
    { char: "🥛", tags: "leche vaso", cat: "comida" },
    { char: "☕", tags: "cafe mañana", cat: "comida" },
    { char: "🍵", tags: "te verde", cat: "comida" },
    { char: "🍶", tags: "sake japones", cat: "comida" },
    { char: "🍾", tags: "champaña botella", cat: "comida" },
    { char: "🍷", tags: "vino copa", cat: "comida" },
    { char: "🍸", tags: "coctel copa", cat: "comida" },
    { char: "🍹", tags: "jugo coctel", cat: "comida" },
    { char: "🍺", tags: "cerveza jarra", cat: "comida" },
    { char: "🍻", tags: "cervezas brindis", cat: "comida" },
    { char: "🥂", tags: "copas brindis", cat: "comida" },
    { char: "🥃", tags: "whisky vaso", cat: "comida" },
    { char: "🥤", tags: "soda vaso", cat: "comida" },
    { char: "🧃", tags: "jugo caja", cat: "comida" },
    { char: "🧉", tags: "mate bebida", cat: "comida" },
    { char: "🧊", tags: "hielo frio", cat: "comida" },
    { char: "🥢", tags: "palillos chinos", cat: "comida" },
    { char: "🍽️", tags: "plato cubiertos", cat: "comida" },
    { char: " Ten", char: "🍴", tags: "tenedor cuchillo", cat: "comida" },
    { char: "🥄", tags: "cuchara", cat: "comida" },

    // --- VIAJES ---
    { char: "🗺️", tags: "mapa mundo", cat: "viajes" },
    { char: "🗾", tags: "japon mapa", cat: "viajes" },
    { char: "🧭", tags: "brujula norte", cat: "viajes" },
    { char: "🏔️", tags: "montaña nieve", cat: "viajes" },
    { char: "⛰️", tags: "montaña", cat: "viajes" },
    { char: "🌋", tags: "volcan lava", cat: "viajes" },
    { char: "🗻", tags: "monte fuji", cat: "viajes" },
    { char: "🏕️", tags: "camping tienda", cat: "viajes" },
    { char: "🏖️", tags: "playa sol", cat: "viajes" },
    { char: "🏜️", tags: "desierto cactus", cat: "viajes" },
    { char: "🏝️", tags: "isla palmera", cat: "viajes" },
    { char: "🏞️", tags: "parque nacional", cat: "viajes" },
    { char: "🏟️", tags: "estadio futbol", cat: "viajes" },
    { char: "🏛️", tags: "edificio griego", cat: "viajes" },
    { char: "🏗️", tags: "obra construccion", cat: "viajes" },
    { char: "🧱", tags: "ladrillo pared", cat: "viajes" },
    { char: "🏘️", tags: "casas barrio", cat: "viajes" },
    { char: "🏚️", tags: "casa abandonada", cat: "viajes" },
    { char: "🏠", tags: "casa hogar", cat: "viajes" },
    { char: "🏡", tags: "casa jardin", cat: "viajes" },
    { char: "🏢", tags: "oficina edificio", cat: "viajes" },
    { char: "🏣", tags: "correo japon", cat: "viajes" },
    { char: "🏤", tags: "correo edificio", cat: "viajes" },
    { char: "🏥", tags: "hospital salud", cat: "viajes" },
    { char: "🏦", tags: "banco dinero", cat: "viajes" },
    { char: "🏨", tags: "hotel dormir", cat: "viajes" },
    { char: "🏩", tags: "hotel amor", cat: "viajes" },
    { char: "🏪", tags: "tienda abierta", cat: "viajes" },
    { char: "🏫", tags: "escuela colegio", cat: "viajes" },
    { char: "🏬", tags: "almacen tienda", cat: "viajes" },
    { char: "🏭", tags: "fabrica humo", cat: "viajes" },
    { char: "🏮", tags: "linterna roja", cat: "viajes" },
    { char: "🏯", tags: "castillo japones", cat: "viajes" },
    { char: "🏰", tags: "castillo europeo", cat: "viajes" },
    { char: "💒", tags: "boda iglesia", cat: "viajes" },
    { char: "🗼", tags: "torre tokio", cat: "viajes" },
    { char: "🗽", tags: "estatua libertad", cat: "viajes" },
    { char: "⛪", tags: "iglesia", cat: "viajes" },
    { char: "🕌", tags: "mezquita", cat: "viajes" },
    { char: "🛕", tags: "templo hindu", cat: "viajes" },
    { char: "🕍", tags: "sinagoga", cat: "viajes" },
    { char: "⛩️", tags: "santuario sintoista", cat: "viajes" },
    { char: "🕋", tags: "kaaba", cat: "viajes" },
    { char: "⛲", tags: "fuente parque", cat: "viajes" },
    { char: "⛺", tags: "tienda campaña", cat: "viajes" },
    { char: "🌁", tags: "puente niebla", cat: "viajes" },
    { char: "🌃", tags: "noche ciudad estrellas", cat: "viajes" },
    { char: "🏙️", tags: "ciudad edificios", cat: "viajes" },
    { char: "🌄", tags: "amanecer montaña", cat: "viajes" },
    { char: "🌅", tags: "amanecer mar", cat: "viajes" },
    { char: "🌆", tags: "ciudad atardecer", cat: "viajes" },
    { char: "🌇", tags: "atardecer sol", cat: "viajes" },
    { char: "🌉", tags: "puente noche", cat: "viajes" },
    { char: "🌌", tags: "galaxia noche", cat: "viajes" },
    { char: "🎠", tags: "tiovivo feria", cat: "viajes" },
    { char: "🎡", tags: "noria feria", cat: "viajes" },
    { char: "🎢", tags: "montaña rusa feria", cat: "viajes" },
    { char: "🚂", tags: "locomotora tren", cat: "viajes" },
    { char: "🚃", tags: "vagon tren", cat: "viajes" },
    { char: "🚄", tags: "tren bala", cat: "viajes" },
    { char: "🚅", tags: "tren rapido", cat: "viajes" },
    { char: "🚆", tags: "tren", cat: "viajes" },
    { char: "🚇", tags: "metro", cat: "viajes" },
    { char: "🚈", tags: "tren ligero", cat: "viajes" },
    { char: "🚉", tags: "estacion tren", cat: "viajes" },
    { char: "🚊", tags: "tranvia", cat: "viajes" },
    { char: "🚝", tags: "monorrail", cat: "viajes" },
    { char: "🚞", tags: "funicular", cat: "viajes" },
    { char: "🚋", tags: "vagon tranvia", cat: "viajes" },
    { char: "🚌", tags: "autobus bus", cat: "viajes" },
    { char: "🚍", tags: "autobus frente", cat: "viajes" },
    { char: "🚎", tags: "trolleybus", cat: "viajes" },
    { char: "🚐", tags: "minibus furgoneta", cat: "viajes" },
    { char: "🚑", tags: "ambulancia", cat: "viajes" },
    { char: "🚒", tags: "bomberos camión", cat: "viajes" },
    { char: "🚓", tags: "policía coche", cat: "viajes" },
    { char: "🚔", tags: "policía frente", cat: "viajes" },
    { char: "🚕", tags: "taxi coche", cat: "viajes" },
    { char: "🚖", tags: "taxi frente", cat: "viajes" },
    { char: "🚗", tags: "coche auto vehiculo", cat: "viajes" },
    { char: "🚘", tags: "coche frente", cat: "viajes" },
    { char: "🚙", tags: "todoterreno coche", cat: "viajes" },
    { char: "🚚", tags: "camión entrega", cat: "viajes" },
    { char: "🚛", tags: "camión articulado", cat: "viajes" },
    { char: "🚜", tags: "tractor campo", cat: "viajes" },
    { char: "🏎️", tags: "fórmula 1 coche carrera", cat: "viajes" },
    { char: "🏍️", tags: "moto motocicleta", cat: "viajes" },
    { char: "🛵", tags: "scooter vespa", cat: "viajes" },
    { char: "🚲", tags: "bicicleta bici", cat: "viajes" },
    { char: "🛴", tags: "patinete", cat: "viajes" },
    { char: "🛹", tags: "skate", cat: "viajes" },
    { char: "🚏", tags: "parada bus", cat: "viajes" },
    { char: "🛤️", tags: "vias tren", cat: "viajes" },
    { char: "⛽", tags: "gasolinera", cat: "viajes" },
    { char: "🚨", tags: "sirena policia", cat: "viajes" },
    { char: "🚥", tags: "semaforo", cat: "viajes" },
    { char: "🚦", tags: "semaforo vertical", cat: "viajes" },
    { char: "🚧", tags: "construccion", cat: "viajes" },
    { char: "⚓", tags: "ancla barco", cat: "viajes" },
    { char: "⛵", tags: "velero barco", cat: "viajes" },
    { char: "🚤", tags: "lancha rapida", cat: "viajes" },
    { char: "🛳️", tags: "crucero barco", cat: "viajes" },
    { char: "⛴️", tags: "ferry barco", cat: "viajes" },
    { char: "🚢", tags: "barco carga", cat: "viajes" },
    { char: "✈️", tags: "avion volar", cat: "viajes" },
    { char: "🛩️", tags: "avioneta", cat: "viajes" },
    { char: "🛫", tags: "avion despegando", cat: "viajes" },
    { char: "🛬", tags: "avion aterrizando", cat: "viajes" },
    { char: "💺", tags: "asiento avion", cat: "viajes" },
    { char: "🚁", tags: "helicoptero", cat: "viajes" },
    { char: "🚟", tags: "ferrocarril suspendido", cat: "viajes" },
    { char: "🚠", tags: "teleferico montaña", cat: "viajes" },
    { char: "🚡", tags: "teleferico ciudad", cat: "viajes" },
    { char: "🛰️", tags: "satelite espacio", cat: "viajes" },
    { char: "🚀", tags: "cohete espacio despegar", cat: "viajes" },
    { char: "🛸", tags: "ovni alien", cat: "viajes" },

    // --- BANDERAS ---
// ==========================================
// LOTE DE BANDERAS COMPLETO (emojiData)
// ==========================================
{ char: "🏁", cat: "banderas", tags: "bandera carreras meta fin ajedrez automovilismo" },
{ char: "🚩", cat: "banderas", tags: "bandera roja aviso alerta ubicacion destino" },
{ char: "🎌", cat: "banderas", tags: "banderas cruzadas japon celebracion" },
{ char: "🏴", cat: "banderas", tags: "bandera negra luto pirata" },
{ char: "🏳️", cat: "banderas", tags: "bandera blanca paz rendicion" },
{ char: "🏳️‍🌈", cat: "banderas", tags: "bandera arcoiris lgbt orgullo diversidad" },
{ char: "🏳️‍⚧️", cat: "banderas", tags: "bandera trans transgender orgullo diversidad" },
{ char: "🏴‍☠️", cat: "banderas", tags: "bandera pirata calavera barco peligro" },
{ char: "🇦🇨", cat: "banderas", tags: "bandera ac ascension isla" },
{ char: "🇦🇩", cat: "banderas", tags: "bandera ad andorra europa" },
{ char: "🇦🇪", cat: "banderas", tags: "bandera ae emiratos arabes unidos dubai" },
{ char: "🇦🇫", cat: "banderas", tags: "bandera af afganistan" },
{ char: "🇦🇬", cat: "banderas", tags: "bandera ag antigua barbuda caribe" },
{ char: "🇦🇮", cat: "banderas", tags: "bandera ai anguila isla" },
{ char: "🇦🇱", cat: "banderas", tags: "bandera al albania europa" },
{ char: "🇦🇲", cat: "banderas", tags: "bandera am armenia" },
{ char: "🇦🇴", cat: "banderas", tags: "bandera ao angola africa" },
{ char: "🇦🇶", cat: "banderas", tags: "bandera aq antartida frio" },
{ char: "🇦🇷", cat: "banderas", tags: "bandera ar argentina sudamerica messi" },
{ char: "🇦🇸", cat: "banderas", tags: "bandera as samoa americana" },
{ char: "🇦🇹", cat: "banderas", tags: "bandera at austria europa" },
{ char: "🇦🇺", cat: "banderas", tags: "bandera au australia" },
{ char: "🇦🇼", cat: "banderas", tags: "bandera aw aruba caribe" },
{ char: "🇦🇽", cat: "banderas", tags: "bandera ax islas aland" },
{ char: "🇦🇿", cat: "banderas", tags: "bandera az azerbaiyan" },
{ char: "🇧🇦", cat: "banderas", tags: "bandera ba bosnia herzegovina" },
{ char: "🇧🇧", cat: "banderas", tags: "bandera bb barbados" },
{ char: "🇧🇩", cat: "banderas", tags: "bandera bd bangladesh" },
{ char: "🇧🇪", cat: "banderas", tags: "bandera be belgica europa" },
{ char: "🇧🇫", cat: "banderas", tags: "bandera bf burkina faso" },
{ char: "🇧🇬", cat: "banderas", tags: "bandera bg bulgaria europa" },
{ char: "🇧🇭", cat: "banderas", tags: "bandera bh bahrein" },
{ char: "🇧🇮", cat: "banderas", tags: "bandera bi burundi" },
{ char: "🇧🇯", cat: "banderas", tags: "bandera bj benin" },
{ char: "🇧嫌", cat: "banderas", tags: "bandera bl san bartolome" },
{ char: "🇧🇲", cat: "banderas", tags: "bandera bm bermudas" },
{ char: "🇧🇳", cat: "banderas", tags: "bandera bn brunei" },
{ char: "🇧🇴", cat: "banderas", tags: "bandera bo bolivia sudamerica cochabamba" },
{ char: "🇧🇶", cat: "banderas", tags: "bandera bq caribe neerlandes Bonaire" },
{ char: "🇧🇷", cat: "banderas", tags: "bandera br brasil sudamerica" },
{ char: "🇧🇸", cat: "banderas", tags: "bandera bs bahamas" },
{ char: "🇧🇹", cat: "banderas", tags: "bandera bt bhutan" },
{ char: "🇧🇻", cat: "banderas", tags: "bandera bv isla bouvet" },
{ char: "🇧🇼", cat: "banderas", tags: "bandera bw botswana" },
{ char: "🇧🇾", cat: "banderas", tags: "bandera by bielorrusia" },
{ char: "🇧🇿", cat: "banderas", tags: "bandera bz belice centroamerica" },
{ char: "🇨🇦", cat: "banderas", tags: "bandera ca canada norteamerica" },
{ char: "🇨🇨", cat: "banderas", tags: "bandera cc islas cocos" },
{ char: "🇨🇩", cat: "banderas", tags: "bandera cd congo" },
{ char: "🇨🇫", cat: "banderas", tags: "bandera cf republica centroafricana" },
{ char: "🇨🇬", cat: "banderas", tags: "bandera cg congo republica" },
{ char: "🇨🇭", cat: "banderas", tags: "bandera ch suiza europa" },
{ char: "🇨🇮", cat: "banderas", tags: "bandera ci costa de marfil" },
{ char: "🇨🇰", cat: "banderas", tags: "bandera ck islas cook" },
{ char: "🇨🇱", cat: "banderas", tags: "bandera cl chile sudamerica" },
{ char: "🇨🇲", cat: "banderas", tags: "bandera cm camerun" },
{ char: "🇨🇳", cat: "banderas", tags: "bandera cn china asia" },
{ char: "🇨🇴", cat: "banderas", tags: "bandera co colombia sudamerica" },
{ char: "🇨🇵", cat: "banderas", tags: "bandera cp isla clipperton" },
{ char: "🇨🇶", cat: "banderas", tags: "bandera cq isla diego garcia" },
{ char: "🇨🇷", cat: "banderas", tags: "bandera cr costa rica centroamerica" },
{ char: "🇨🇺", cat: "banderas", tags: "bandera cu cuba caribe" },
{ char: "🇨🇻", cat: "banderas", tags: "bandera cv cabo verde" },
{ char: "🇨🇼", cat: "banderas", tags: "bandera cw curazao" },
{ char: "🇨🇽", cat: "banderas", tags: "bandera cx isla de navidad" },
{ char: "🇨🇾", cat: "banderas", tags: "bandera cy chipre" },
{ char: "🇨🇿", cat: "banderas", tags: "bandera cz republica checa europa" },
{ char: "🇩🇪", cat: "banderas", tags: "bandera de alemania europa" },
{ char: "🇩🇬", cat: "banderas", tags: "bandera dg diego garcia" },
{ char: "🇩🇯", cat: "banderas", tags: "bandera dj yibuti" },
{ char: "🇩🇰", cat: "banderas", tags: "bandera dk dinamarca europa" },
{ char: "🇩🇲", cat: "banderas", tags: "bandera dm dominica" },
{ char: "🇩🇴", cat: "banderas", tags: "bandera do republica dominicana caribe" },
{ char: "🇩🇿", cat: "banderas", tags: "bandera dz argelia" },
{ char: "🇪🇦", cat: "banderas", tags: "bandera ea ceuta melilla" },
{ char: "🇪🇨", cat: "banderas", tags: "bandera ec ecuador sudamerica" },
{ char: "🇪🇪", cat: "banderas", tags: "bandera ee estonia europa" },
{ char: "🇪🇬", cat: "banderas", tags: "bandera eg egipto" },
{ char: "🇪🇭", cat: "banderas", tags: "bandera eh sahara occidental" },
{ char: "🇪🇷", cat: "banderas", tags: "bandera er eritrea" },
{ char: "🇪🇸", cat: "banderas", tags: "bandera es españa europa" },
{ char: "🇪🇹", cat: "banderas", tags: "bandera et etiopia" },
{ char: "🇪🇺", cat: "banderas", tags: "bandera eu union europea europa" },
{ char: "🇫🇮", cat: "banderas", tags: "bandera fi finlandia europa" },
{ char: "🇫🇯", cat: "banderas", tags: "bandera fj fiji" },
{ char: "🇫🇰", cat: "banderas", tags: "bandera fk islas malvinas falkland" },
{ char: "🇫🇲", cat: "banderas", tags: "bandera fm micronesia" },
{ char: "🇫🇴", cat: "banderas", tags: "bandera fo islas feroe" },
{ char: "🇫🇷", cat: "banderas", tags: "bandera fr francia europa" },
{ char: "🇬🇦", cat: "banderas", tags: "bandera ga gabon" },
{ char: "🇬🇧", cat: "banderas", tags: "bandera gb reino unido inglaterra uk" },
{ char: "🇬🇩", cat: "banderas", tags: "bandera gd granada" },
{ char: "🇬🇪", cat: "banderas", tags: "bandera ge georgia" },
{ char: "🇬🇫", cat: "banderas", tags: "bandera gf guayana francesa" },
{ char: "🇬🇬", cat: "banderas", tags: "bandera gg guernsey" },
{ char: "🇬🇭", cat: "banderas", tags: "bandera gh ghana" },
{ char: "🇬🇮", cat: "banderas", tags: "bandera gi gibraltar" },
{ char: "🇬🇱", cat: "banderas", tags: "bandera gl groenlandia" },
{ char: "🇬🇲", cat: "banderas", tags: "bandera gm gambia" },
{ char: "🇬🇳", cat: "banderas", tags: "bandera gn guinea" },
{ char: "🇬🇵", cat: "banderas", tags: "bandera gp guadalupe" },
{ char: "🇬🇶", cat: "banderas", tags: "bandera gq guinea ecuatorial" },
{ char: "🇬🇷", cat: "banderas", tags: "bandera gr grecia europa" },
{ char: "🇬🇸", cat: "banderas", tags: "bandera gs islas georgias del sur" },
{ char: "🇬🇹", cat: "banderas", tags: "bandera gt guatemala centroamerica" },
{ char: "🇬🇺", cat: "banderas", tags: "bandera gu guam" },
{ char: "🇬🇼", cat: "banderas", tags: "bandera gw guinea bissau" },
{ char: "🇬🇾", cat: "banderas", tags: "bandera gy guyana" },
{ char: "🇭🇰", cat: "banderas", tags: "bandera hk hong kong" },
{ char: "🇭🇲", cat: "banderas", tags: "bandera hm islas heard mcdonald" },
{ char: "🇭🇳", cat: "banderas", tags: "bandera hn honduras centroamerica" },
{ char: "🇭🇷", cat: "banderas", tags: "bandera hr croacia europa" },
{ char: "🇭🇹", cat: "banderas", tags: "bandera ht haiti" },
{ char: "🇭🇺", cat: "banderas", tags: "bandera hu hungria europa" },
{ char: "🇮🇨", cat: "banderas", tags: "bandera ic islas canarias" },
{ char: "🇮🇩", cat: "banderas", tags: "bandera id indonesia" },
{ char: "🇮🇪", cat: "banderas", tags: "bandera ie irlanda europa" },
{ char: "🇮🇱", cat: "banderas", tags: "bandera il israel" },
{ char: "🇮🇲", cat: "banderas", tags: "bandera im isla de man" },
{ char: "🇮🇳", cat: "banderas", tags: "bandera in india" },
{ char: "🇮🇴", cat: "banderas", tags: "bandera io territorio britanico oceano indico" },
{ char: "🇮🇶", cat: "banderas", tags: "bandera iq irak" },
{ char: "🇮🇷", cat: "banderas", tags: "bandera ir iran" },
{ char: "🇮🇸", cat: "banderas", tags: "bandera is islandia" },
{ char: "🇮🇹", cat: "banderas", tags: "bandera it italia europa" },
{ char: "🇯🇪", cat: "banderas", tags: "bandera je jersey" },
{ char: "🇯🇲", cat: "banderas", tags: "bandera jm jamaica caribe" },
{ char: "🇯🇴", cat: "banderas", tags: "bandera jo jordania" },
{ char: "🇯🇵", cat: "banderas", tags: "bandera jp japon asia" },
{ char: "🇰🇪", cat: "banderas", tags: "bandera ke kenia" },
{ char: "🇰🇬", cat: "banderas", tags: "bandera kg kirguistan" },
{ char: "🇰🇭", cat: "banderas", tags: "bandera kh camboya" },
{ char: "🇰🇮", cat: "banderas", tags: "bandera ki kiribati" },
{ char: "🇰🇲", cat: "banderas", tags: "bandera km comoras" },
{ char: "🇰🇳", cat: "banderas", tags: "bandera kn san cristobal nieves" },
{ char: "🇰🇵", cat: "banderas", tags: "bandera kp corea del norte" },
{ char: "🇰🇷", cat: "banderas", tags: "bandera kr corea del sur" },
{ char: "🇰🇼", cat: "banderas", tags: "bandera kw kuwait" },
{ char: "🇰🇾", cat: "banderas", tags: "bandera ky islas caiman" },
{ char: "🇰🇿", cat: "banderas", tags: "bandera kz kazajistan" },
{ char: "🇱🇦", cat: "banderas", tags: "bandera la laos" },
{ char: "🇱🇧", cat: "banderas", tags: "bandera lb libano" },
{ char: "🇱🇨", cat: "banderas", tags: "bandera lc santa lucia" },
{ char: "🇱🇮", cat: "banderas", tags: "bandera li liechtenstein" },
{ char: "🇱🇰", cat: "banderas", tags: "bandera lk sri lanka" },
{ char: "🇱🇷", cat: "banderas", tags: "bandera lr liberia" },
{ char: "🇱🇸", cat: "banderas", tags: "bandera ls lesotho" },
{ char: "🇱🇹", cat: "banderas", tags: "bandera lt lituania europa" },
{ char: "🇱🇺", cat: "banderas", tags: "bandera lu luxemburgo europa" },
{ char: "🇱🇻", cat: "banderas", tags: "bandera lv letonia europa" },
{ char: "🇱🇾", cat: "banderas", tags: "bandera ly libia" },
{ char: "🇲🇦", cat: "banderas", tags: "bandera ma marruecos" },
{ char: "🇲🇨", cat: "banderas", tags: "bandera mc monaco" },
{ char: "🇲🇩", cat: "banderas", tags: "bandera md moldavia" },
{ char: "🇲🇪", cat: "banderas", tags: "bandera me montenegro" },
{ char: "🇲🇫", cat: "banderas", tags: "bandera mf san martin" },
{ char: "🇲🇬", cat: "banderas", tags: "bandera mg madagascar" },
{ char: "🇲🇭", cat: "banderas", tags: "bandera mh islas marshall" },
{ char: "🇲🇰", cat: "banderas", tags: "bandera mk macedonia" },
{ char: "🇲🇱", cat: "banderas", tags: "bandera ml mali" },
{ char: "🇲🇲", cat: "banderas", tags: "bandera mm Myanmar birmania" },
{ char: "🇲🇳", cat: "banderas", tags: "bandera mn mongolia" },
{ char: "🇲🇴", cat: "banderas", tags: "bandera mo macao" },
{ char: "🇲🇵", cat: "banderas", tags: "bandera mp islas marianas" },
{ char: "🇲🇶", cat: "banderas", tags: "bandera mq martinica" },
{ char: "🇲🇷", cat: "banderas", tags: "bandera mr mauritania" },
{ char: "🇲🇸", cat: "banderas", tags: "bandera ms montserrat" },
{ char: "🇲🇹", cat: "banderas", tags: "bandera mt malta" },
{ char: "🇲🇺", cat: "banderas", tags: "bandera mu mauricio" },
{ char: "🇲🇻", cat: "banderas", tags: "bandera mv maldivas" },
{ char: "🇲🇼", cat: "banderas", tags: "bandera mw malaui" },
{ char: "🇲🇽", cat: "banderas", tags: "bandera mx mexico norteamerica" },
{ char: "🇲🇾", cat: "banderas", tags: "bandera my malasia" },
{ char: "🇲🇿", cat: "banderas", tags: "bandera mz mozambique" },
{ char: "🇳🇦", cat: "banderas", tags: "bandera na namibia" },
{ char: "🇳🇨", cat: "banderas", tags: "bandera nc nueva caledonia" },
{ char: "🇳🇪", cat: "banderas", tags: "bandera ne niger" },
{ char: "🇳🇫", cat: "banderas", tags: "bandera nf isla norfolk" },
{ char: "🇳🇬", cat: "banderas", tags: "bandera ng nigeria" },
{ char: "🇳🇮", cat: "banderas", tags: "bandera ni nicaragua centroamerica" },
{ char: "🇳🇱", cat: "banderas", tags: "bandera nl holanda paises bajos europa" },
{ char: "🇳🇴", cat: "banderas", tags: "bandera no noruega europa" },
{ char: "🇳🇵", cat: "banderas", tags: "bandera np nepal" },
{ char: "🇳🇷", cat: "banderas", tags: "bandera nr nauru" },
{ char: "🇳🇺", cat: "banderas", tags: "bandera nu niue" },
{ char: "🇳🇿", cat: "banderas", tags: "bandera nz nueva zelanda" },
{ char: "🇴🇲", cat: "banderas", tags: "bandera om oman" },
{ char: "🇵🇦", cat: "banderas", tags: "bandera pa panama centroamerica" },
{ char: "🇵🇪", cat: "banderas", tags: "bandera pe peru sudamerica" },
{ char: "🇵🇫", cat: "banderas", tags: "bandera pf polinesia francesa" },
{ char: "🇵🇬", cat: "banderas", tags: "bandera pg papua nueva guinea" },
{ char: "🇵🇭", cat: "banderas", tags: "bandera ph filipinas" },
{ char: "🇵🇰", cat: "banderas", tags: "bandera pk pakistan" },
{ char: "🇵🇱", cat: "banderas", tags: "bandera pl polonia europa" },
{ char: "🇵🇲", cat: "banderas", tags: "bandera pm san pedro miquelon" },
{ char: "🇵🇳", cat: "banderas", tags: "bandera pn islas pitcairn" },
{ char: "🇵🇷", cat: "banderas", tags: "bandera pr puerto rico caribe" },
{ char: "🇵🇸", cat: "banderas", tags: "bandera ps palestina" },
{ char: "🇵🇹", cat: "banderas", tags: "bandera pt portugal europa" },
{ char: "🇵🇼", cat: "banderas", tags: "bandera pw palaos" },
{ char: "🇵🇾", cat: "banderas", tags: "bandera py paraguay sudamerica" },
{ char: "🇶🇦", cat: "banderas", tags: "bandera qa qatar katar" },
{ char: "🇷🇪", cat: "banderas", tags: "bandera re reunion" },
{ char: "🇷🇴", cat: "banderas", tags: "bandera ro rumania europa" },
{ char: "🇷🇸", cat: "banderas", tags: "bandera rs serbia" },
{ char: "🇷🇺", cat: "banderas", tags: "bandera ru rusia" },
{ char: "🇷🇼", cat: "banderas", tags: "bandera rw ruanda" },
{ char: "🇸🇦", cat: "banderas", tags: "bandera sa arabia saudita" },
{ char: "🇸🇧", cat: "banderas", tags: "bandera sb islas salomon" },
{ char: "🇸🇨", cat: "banderas", tags: "bandera sc seychelles" },
{ char: "🇸🇩", cat: "banderas", tags: "bandera sd sudan" },
{ char: "🇸🇪", cat: "banderas", tags: "bandera se suecia europa" },
{ char: "🇸🇬", cat: "banderas", tags: "bandera sg singapur" },
{ char: "🇸🇭", cat: "banderas", tags: "bandera sh santa elena" },
{ char: "🇸🇮", cat: "banderas", tags: "bandera si eslovenia europa" },
{ char: "🇸🇯", cat: "banderas", tags: "bandera sj svalbard jan mayen" },
{ char: "🇸🇰", cat: "banderas", tags: "bandera sk eslovaquia europa" },
{ char: "🇸🇱", cat: "banderas", tags: "bandera sl sierra leona" },
{ char: "🇸🇲", cat: "banderas", tags: "bandera sm san marino" },
{ char: "🇸🇳", cat: "banderas", tags: "bandera sn senegal" },
{ char: "🇸🇴", cat: "banderas", tags: "bandera so somalia" },
{ char: "🇸🇷", cat: "banderas", tags: "bandera sr surinam" },
{ char: "🇸🇸", cat: "banderas", tags: "bandera ss sudan del sur" },
{ char: "🇸🇹", cat: "banderas", tags: "bandera st santo tome principe" },
{ char: "🇸🇻", cat: "banderas", tags: "bandera sv el salvador centroamerica" },
{ char: "🇸🇽", cat: "banderas", tags: "bandera sx san martin neerlandes" },
{ char: "🇸🇾", cat: "banderas", tags: "bandera sy siria" },
{ char: "🇸🇿", cat: "banderas", tags: "bandera sz suazilandia" },
{ char: "🇹🇦", cat: "banderas", tags: "bandera ta tristan da cunha" },
{ char: "🇹🇨", cat: "banderas", tags: "bandera tc islas turcas caicos" },
{ char: "🇹🇩", cat: "banderas", tags: "bandera td chad" },
{ char: "🇹🇫", cat: "banderas", tags: "bandera tf tierras australes francesas" },
{ char: "🇹🇬", cat: "banderas", tags: "bandera tg togo" },
{ char: "🇹🇭", cat: "banderas", tags: "bandera th tailandia" },
{ char: "🇹🇯", cat: "banderas", tags: "bandera tj tayikistan" },
{ char: "🇹🇰", cat: "banderas", tags: "bandera tk tokelau" },
{ char: "🇹🇱", cat: "banderas", tags: "bandera tl timor oriental" },
{ char: "🇹🇲", cat: "banderas", tags: "bandera tm turkmenistan" },
{ char: "🇹🇳", cat: "banderas", tags: "bandera tn tunez" },
{ char: "🇹🇴", cat: "banderas", tags: "bandera to tonga" },
{ char: "🇹🇷", cat: "banderas", tags: "bandera tr turquia" },
{ char: "🇹🇹", cat: "banderas", tags: "bandera tt trinidad tobago" },
{ char: "🇹🇻", cat: "banderas", tags: "bandera tv tuvalu" },
{ char: "🇹🇼", cat: "banderas", tags: "bandera tw taiwan" },
{ char: "🇹🇿", cat: "banderas", tags: "bandera tz tanzania" },
{ char: "🇺🇦", cat: "banderas", tags: "bandera ua ucrania europa" },
{ char: "🇺🇬", cat: "banderas", tags: "bandera ug uganda" },
{ char: "🇺🇲", cat: "banderas", tags: "bandera um islas menores alejadas eeuu" },
{ char: "🇺🇳", cat: "banderas", tags: "bandera un naciones unidas onu" },
{ char: "🇺🇸", cat: "banderas", tags: "bandera us estados unidos eeuu usa norteamerica" },
{ char: "🇺🇾", cat: "banderas", tags: "bandera uy uruguay sudamerica" },
{ char: "🇺🇿", cat: "banderas", tags: "bandera uz uzbekistan" },
{ char: "🇻🇦", cat: "banderas", tags: "bandera va vaticano" },
{ char: "🇻🇨", cat: "banderas", tags: "bandera vc san vicente granadinas" },
{ char: "🇻🇪", cat: "banderas", tags: "bandera ve venezuela sudamerica" },
{ char: "🇻🇬", cat: "banderas", tags: "bandera vg islas virgenes britanicas" },
{ char: "🇻🇮", cat: "banderas", tags: "bandera vi islas virgenes eeuu" },
{ char: "🇻🇳", cat: "banderas", tags: "bandera vn vietnam" },
{ char: "🇻🇺", cat: "banderas", tags: "bandera vu vanuatu" },
{ char: "🇼🇫", cat: "banderas", tags: "bandera wf wallis futuna" },
{ char: "🇼🇸", cat: "banderas", tags: "bandera ws samoa" },
{ char: "🇽🇰", cat: "banderas", tags: "bandera xk kosovo" },
{ char: "🇾🇪", cat: "banderas", tags: "bandera ye yemen" },
{ char: "🇾🇹", cat: "banderas", tags: "bandera yt mayotte" },
{ char: "🇿🇦", cat: "banderas", tags: "bandera za sudafrica" },
{ char: "🇿🇲", cat: "banderas", tags: "bandera zm zambia" },
{ char: "🇿🇼", cat: "banderas", tags: "bandera zw zimbabue" },
{ char: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", cat: "banderas", tags: "bandera inglaterra uk reino unido" },
{ char: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", cat: "banderas", tags: "bandera escocia uk reino unido" },
{ char: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", cat: "banderas", tags: "bandera gales uk reino unido" },

    // --- HERRAMIENTAS ---
    { char: "🛠️", tags: "herramientas soporte reparar", cat: "herramientas" },
    { char: "🔧", tags: "llave inglesa ajustar", cat: "herramientas" },
    { char: "⚙️", tags: "engranaje ajustes configuracion", cat: "herramientas" },
    { char: "🔨", tags: "martillo", cat: "herramientas" },
    { char: "🧰", tags: "caja herramientas", cat: "herramientas" },
    { char: "💻", tags: "laptop ordenador computadora pc mac", cat: "herramientas" },
    { char: "🖥️", tags: "monitor pantalla escritorio", cat: "herramientas" },
    { char: "⌨️", tags: "teclado escribir", cat: "herramientas" },
    { char: "🖱️", tags: "raton mouse click", cat: "herramientas" },
    { char: "🖨️", tags: "impresora papel copia", cat: "herramientas" },
    { char: "📱", tags: "celular movil smartphone iphone", cat: "herramientas" },
    { char: "☎️", tags: "telefono llamada contacto", cat: "herramientas" },
    { char: "📞", tags: "auricular soporte servicio", cat: "herramientas" },
    { char: "🔋", tags: "bateria carga energia", cat: "herramientas" },
    { char: "🔌", tags: "enchufe conector electricidad", cat: "herramientas" },
    { char: "💡", tags: "bombilla luz idea brillante", cat: "herramientas" },
    { char: "🔦", tags: "linterna luz buscar", cat: "herramientas" },
    { char: "🔍", tags: "lupa buscar encontrar", cat: "herramientas" },
    { char: "🔑", tags: "llave acceso abrir", cat: "herramientas" },
    { char: "🔨", tags: "martillo herramienta construir", cat: "herramientas" },
    { char: "🛠️", tags: "herramientas soporte reparar", cat: "herramientas" },
    { char: "🔧", tags: "llave inglesa ajustar", cat: "herramientas" },
    { char: "⚙️", tags: "engranaje ajustes configuracion", cat: "herramientas" },
    { char: "🧰", tags: "caja herramientas", cat: "herramientas" },
    { char: "📡", tags: "antena satelite señal", cat: "herramientas" },
    { char: "💉", tags: "jeringa vacuna salud", cat: "herramientas" },
    { char: "💊", tags: "pastilla medicina salud", cat: "herramientas" },
    { char: "🩺", tags: "estetoscopio medico", cat: "herramientas" },
    { char: "🧹", tags: "escoba limpiar", cat: "herramientas" },
    { char: "🧯", tags: "extintor fuego seguridad", cat: "herramientas" },

    // --- SIMBOLOS ---
    { char: "⚠️", tags: "atencion advertencia", cat: "simbolos" },
    { char: "❓", tags: "pregunta duda", cat: "simbolos" },
    { char: "❗", tags: "exclamacion alerta", cat: "simbolos" },
    { char: "⚠️", tags: "atencion advertencia cuidado peligro alerta", cat: "simbolos" },
    { char: "🚫", tags: "prohibido no denegado stop", cat: "simbolos" },
    { char: "❌", tags: "error equis no aspa", cat: "simbolos" },
    { char: "⭕", tags: "circulo rojo o ok", cat: "simbolos" },
    { char: "🛑", tags: "stop pare alto", cat: "simbolos" },
    { char: "✅", tags: "check verificado ok hecho", cat: "simbolos" },
    { char: "💹", tags: "grafica mercado subir", cat: "simbolos" },
    { char: "🌐", tags: "web internet global", cat: "simbolos" },
    { char: "⬅️", tags: "flecha izquierda", cat: "simbolos" },
    { char: "⬆️", tags: "flecha arriba", cat: "simbolos" },
    { char: "⬇️", tags: "flecha abajo", cat: "simbolos" },
    { char: "➡️", tags: "flecha derecha", cat: "simbolos" },
    { char: "🔃", tags: "recargar flechas circulo", cat: "simbolos" },
    { char: "➕", tags: "mas suma positivo", cat: "simbolos" },
    { char: "➖", tags: "menos resta negativo", cat: "simbolos" },
    { char: "💲", tags: "dolar dinero precio", cat: "simbolos" },
    
//PROFESIONES
    
{ char: "🧑‍🎓", cat: "profesiones", tags: "estudiante graduado universitario titulo educacion curso academia" },
{ char: "👨‍🎓", cat: "profesiones", tags: "estudiante graduado universitario titulo educacion curso academia" },
{ char: "👩‍🎓", cat: "profesiones", tags: "estudiante graduada universitaria titulo educacion curso academia" },
{ char: "🧑‍⚖️", cat: "profesiones", tags: "juez justicia ley legal abogado derechos" },
{ char: "👨‍⚖️", cat: "profesiones", tags: "juez justicia ley legal abogado derechos" },
{ char: "👩‍⚖️", cat: "profesiones", tags: "juez justicia ley legal abogada derechos" },
{ char: "🧑‍🌾", cat: "profesiones", tags: "agricultor granjero campo naturaleza plantas siembra" },
{ char: "👨‍🌾", cat: "profesiones", tags: "agricultor granjero campo naturaleza plantas siembra" },
{ char: "👩‍🌾", cat: "profesiones", tags: "agricultora granjera campo naturaleza plantas siembra" },
{ char: "🧑‍🍳", cat: "profesiones", tags: "cocinero chef restaurante comida gastronomia negocio" },
{ char: "👨‍🍳", cat: "profesiones", tags: "cocinero chef restaurante comida gastronomia negocio" },
{ char: "👩‍🍳", cat: "profesiones", tags: "cocinera chef restaurante comida gastronomia negocio" },
{ char: "🧑‍🏭", cat: "profesiones", tags: "obrero fabrica manufactura industria produccion empresa" },
{ char: "👨‍🏭", cat: "profesiones", tags: "obrero fabrica manufactura industria produccion empresa" },
{ char: "👩‍🏭", cat: "profesiones", tags: "obrera fabrica manufactura industria produccion empresa" },
{ char: "🧑‍✈️", cat: "profesiones", tags: "piloto avion viaje aerolinea turismo transporte" },
{ char: "👨‍✈️", cat: "profesiones", tags: "piloto avion viaje aerolinea turismo transporte" },
{ char: "👩‍✈️", cat: "profesiones", tags: "piloto avion viaje aerolinea turismo transporte" },
{ char: "🧑‍🚒", cat: "profesiones", tags: "bombero fuego emergencia rescate seguridad" },
{ char: "👨‍🚒", cat: "profesiones", tags: "bombero fuego emergencia rescate seguridad" },
{ char: "👩‍🚒", cat: "profesiones", tags: "bombera fuego emergencia rescate seguridad" },
{ char: "🕵️", cat: "profesiones", tags: "detective espia buscar investigar secreto auditoria" },
{ char: "🕵️‍♂️", cat: "profesiones", tags: "detective espia buscar investigar secreto auditoria" },
{ char: "🕵️‍♀️", cat: "profesiones", tags: "detective espia buscar investigar secreto auditoria" },
// PERSONAS
{ char: "👋", cat: "personas", tags: "hola adios saludo mano bienvenida despedida" },
{ char: "🖐️", cat: "personas", tags: "mano abierta cinco detener aplauso" },
{ char: "🖖", cat: "personas", tags: "saludo vulcano geek tecnologia exito" },
{ char: "🫱", cat: "personas", tags: "mano derecha ofrecer ayuda conectar" },
{ char: "🫲", cat: "personas", tags: "mano izquierda recibir aceptar" },
{ char: "🫳", cat: "personas", tags: "mano hacia abajo soltar bajar descartar" },
{ char: "🫴", cat: "personas", tags: "mano hacia arriba traer recibir pedir" },
{ char: "🫷", cat: "personas", tags: "empujar izquierda detener barrera limite" },
{ char: "🫸", cat: "personas", tags: "empujar derecha detener barrera limite" },
{ char: "👌", cat: "personas", tags: "ok perfecto bien aprobado correcto excelente" },
{ char: "🤌", cat: "personas", tags: "que quieres que es esto que paso detalle exacto" },
{ char: "🤏", cat: "personas", tags: "un poco poquito pequeño descuento oferta" },
{ char: "✌️", cat: "personas", tags: "paz amor victoria dos exito ganar" },
{ char: "🤞", cat: "personas", tags: "dedos cruzados suerte ojala exito esperanza" },
{ char: "🫰", cat: "personas", tags: "corazon mano dinero amor caro pagar" },
{ char: "🤟", cat: "personas", tags: "te amo rock estilo musica buena onda" },
{ char: "🤘", cat: "personas", tags: "rock cuernos fuerza metal musica" },
{ char: "🤙", cat: "personas", tags: "llamame telefono contacto llamada soporte" },
{ char: "👈", cat: "personas", tags: "mirar izquierda indicador aqui ver" },
{ char: "👉", cat: "personas", tags: "mirar derecha indicador link aqui enlace boton" },
{ char: "👆", cat: "personas", tags: "mirar arriba indicador leer texto importante" },
{ char: "👇", cat: "personas", tags: "mirar abajo link enlace aqui comentar click" },
{ char: "☝️", cat: "personas", tags: "atencion primero una pregunta cuidado" },
{ char: "🫵", cat: "personas", tags: "tu llamado a la accion cliente ideal atencion" },
{ char: "✊", cat: "personas", tags: "puño arriba poder fuerza lucha exito" },
{ char: "👊", cat: "personas", tags: "puñetazo golpe exito choque de puños" },
{ char: "🤛", cat: "personas", tags: "puño izquierda equipo union amigos" },
{ char: "🤜", cat: "personas", tags: "puño derecha equipo union amigos" },
{ char: "🫶", cat: "personas", tags: "manos corazon amor gracias aprecio comunidad" },
{ char: "👐", cat: "personas", tags: "manos abiertas dar recibir transparencia honestidad" },
{ char: "🤲", cat: "personas", tags: "manos juntas pedir recibir orar" },
{ char: "✍️", cat: "personas", tags: "escribir redaccion copy blog firma contrato apuntar" },
{ char: "🤳", cat: "personas", tags: "selfie foto celular redes sociales historias" },
{ char: "🦿", cat: "personas", tags: "protesis pierna robotica avance salud superacion" },
{ char: "👁️", cat: "personas", tags: "ojo mirar ver atencion vigilar review" },
{ char: "👄", cat: "personas", tags: "boca labios hablar testimonio voz" },
{ char: "🫦", cat: "personas", tags: "morder labio deseo interes nervios" },
{ char: "🧔‍♂️", cat: "personas", tags: "hombre con barba perfil cliente adulto" },
{ char: "🧔‍♀️", cat: "personas", tags: "mujer con barba inclusivo perfil" },
{ char: "👴", cat: "personas", tags: "abuelo anciano viejo experiencia jubilado" },
{ char: "👵", cat: "personas", tags: "abuela anciana vieja experiencia jubilada" },
{ char: "🙅‍♂️", cat: "personas", tags: "hombre no prohibido cancelado error detener" },
{ char: "🙅‍♀️", cat: "personas", tags: "mujer no prohibido cancelado error detener" },
{ char: "🙆‍♂️", cat: "personas", tags: "hombre ok aprobado bien correcto si" },
{ char: "🙆‍♀️", cat: "personas", tags: "mujer ok aprobado bien correcto si" },
{ char: "💁‍♂️", cat: "personas", tags: "hombre informacion ayuda soporte servicio" },
{ char: "💁‍♀️", cat: "personas", tags: "mujer informacion ayuda soporte servicio" },
{ char: "🧏‍♂️", cat: "personas", tags: "hombre sordo escuchar atencion" },
{ char: "🧏‍♀️", cat: "personas", tags: "mujer sorda escuchar atencion" },
{ char: "🙇‍♂️", cat: "personas", tags: "hombre disculpa respeto por favor gracias" },
{ char: "🙇‍♀️", cat: "personas", tags: "mujer disculpa respeto por favor gracias" },
{ char: "🥷", cat: "personas", tags: "ninja experto estratega incognito" },
{ char: "🤴", cat: "personas", tags: "principe rey premium VIP calidad" },
{ char: "👸", cat: "personas", tags: "princesa reina premium VIP calidad" },
{ char: "🤵‍♂️", cat: "personas", tags: "hombre elegante traje boda negocio" },
{ char: "🤵‍♀️", cat: "personas", tags: "mujer elegante traje boda negocio" },
{ char: "👰‍♂️", cat: "personas", tags: "hombre novia boda matrimonio" },
{ char: "👰‍♀️", cat: "personas", tags: "mujer novia boda matrimonio" },
{ char: "🤰", cat: "personas", tags: "embarazada madre familia nacimiento" },
{ char: "🫃", cat: "personas", tags: "hombre embarazado familia lleno comida" },
{ char: "👼", cat: "personas", tags: "angel inocencia bebe perfecto" },
{ char: "🎅", cat: "personas", tags: "santa claus papa noel navidad diciembre regalos" },
{ char: "🤶", cat: "personas", tags: "mama noel navidad diciembre regalos" },
{ char: "🦸‍♂️", cat: "personas", tags: "superheroe poder heroe salvar exito" },
{ char: "🦸‍♀️", cat: "personas", tags: "superheroina poder heroe salvar exito" },
{ char: "🦹‍♂️", cat: "personas", tags: "villano enemigo competencia contra" },
{ char: "🦹‍♀️", cat: "personas", tags: "villana enemiga competencia contra" },
{ char: "🧙‍♂️", cat: "personas", tags: "mago truco estrategia magia solucion" },
{ char: "🧙‍♀️", cat: "personas", tags: "maga truco estrategia magia solucion" },
{ char: "🧚‍♂️", cat: "personas", tags: "hada fantasia deseo sueño magico" },
{ char: "🧚‍♀️", cat: "personas", tags: "hada fantasia deseo sueño magico" },
{ char: "🚶‍♂️", cat: "personas", tags: "hombre caminando paso a paso proceso avanzar" },
{ char: "🚶‍♀️", cat: "personas", tags: "mujer caminando paso a paso proceso avanzar" },
{ char: "🚶‍➡️", cat: "personas", tags: "caminando hacia adelante futuro direccion" },
{ char: "🧍‍♂️", cat: "personas", tags: "hombre parado quieto esperar" },
{ char: "🧍‍♀️", cat: "personas", tags: "mujer parada quieta esperar" },
{ char: "🧎‍♂️", cat: "personas", tags: "hombre de rodillas respeto pedir" },
{ char: "🧎‍♀️", cat: "personas", tags: "mujer de rodillas respeto pedir" },
{ char: "🏃‍♂️", cat: "personas", tags: "hombre corriendo rapido velocidad urgente ganar" },
{ char: "🏃‍♀️", cat: "personas", tags: "mujer corriendo rapido velocidad urgente ganar" },
{ char: "🏃‍➡️", cat: "personas", tags: "corriendo hacia adelante meta exito prisa" },
{ char: "💃", cat: "personas", tags: "mujer bailando fiesta celebracion alegria diversion" },
{ char: "🕺", cat: "personas", tags: "hombre bailando fiesta celebracion alegria diversion" },
{ char: "🕴️", cat: "personas", tags: "empresario agente traje negocios secreto" },
{ char: "🧗‍♂️", cat: "personas", tags: "hombre escalando superacion metas exito" },
{ char: "🧗‍♀️", cat: "personas", tags: "mujer escalando superacion metas exito" },
{ char: "🏇", cat: "personas", tags: "carrera caballos ganar velocidad apuestas" },
{ char: "🏌️‍♂️", cat: "personas", tags: "golf hombre deporte negocios millonario" },
{ char: "🏌️‍♀️", cat: "personas", tags: "golf mujer deporte negocios millonaria" },
{ char: "🏄‍♂️", cat: "personas", tags: "surf hombre playa viajes libertad" },
{ char: "🏄‍♀️", cat: "personas", tags: "surf mujer playa viajes libertad" },
{ char: "🏊‍♂️", cat: "personas", tags: "nadar hombre deporte constancia" },
{ char: "🏊‍♀️", cat: "personas", tags: "nadar mujer deporte constancia" },
{ char: "🏋️‍♂️", cat: "personas", tags: "gimnasio hombre pesas entrenamiento disciplina" },
{ char: "🏋️‍♀️", cat: "personas", tags: "gimnasio mujer pesas entrenamiento disciplina" },
{ char: "🚴‍♂️", cat: "personas", tags: "ciclismo hombre bicicleta deporte ruta" },
{ char: "🚴‍♀️", cat: "personas", tags: "ciclismo mujer bicicleta deporte ruta" },
{ char: "🧘‍♂️", cat: "personas", tags: "hombre meditacion relajacion calma enfoque mente" },
{ char: "🧘‍♀️", cat: "personas", tags: "mujer meditacion relajacion calma enfoque mente" },
{ char: "🛌", cat: "personas", tags: "durmiendo cama descansar hotel sueño" },
{ char: "👥", cat: "personas", tags: "grupo equipo comunidad seguidores socios" },
{ char: "🫂", cat: "personas", tags: "abrazo apoyo empatia union clientes gracias" }
      
];
// ==========================================
// 1. SELECTORES
// ==========================================
const composer = document.getElementById('emojiComposer');
const charCounter = document.getElementById('charCounter');
const fontSelector = document.getElementById('fontSelector');
const btnBold = document.getElementById('btnBold');
const btnItalic = document.getElementById('btnItalic');
const grid = document.getElementById('emojiGrid');
const searchInput = document.getElementById('searchInput');
const toast = document.getElementById('toast');

let savedStart = 0;
let savedEnd = 0;

// ==========================================
// 2. DICCIONARIO DE FUENTES (SOPORTE TOTAL: MAYÚS, MINÚS, NÚMEROS, TILDES Y Ñ)
// ==========================================
const fonts = {
    bold: { 
        a:"𝗮",b:"𝗯",c:"𝗰",d:"𝗱",e:"𝗲",f:"𝗳",g:"𝗴",h:"𝗵",i:"𝗶",j:"𝗷",k:"𝗸",l:"𝗹",m:"𝗺",n:"𝗻",o:"𝗼",p:"𝗽",q:"𝗾",r:"𝗿",s:"𝘀",t:"𝘁",u:"𝘂",v:"𝘃",w:"𝘄",x:"𝘅",y:"𝘆",z:"𝘇", 
        A:"𝗔",B:"𝗕",C:"𝗖",D:"𝗗",E:"𝗘",F:"𝗙",G:"𝗚",H:"𝗛",I:"𝗜",J:"𝗝",K:"𝗞",L:"𝗟",M:"𝗠",N:"𝗡",O:"𝗢",P:"𝗣",Q:"𝗤",R:"𝗥",S:"𝗦",T:"𝗧",U:"𝗨",V:"𝗩",W:"𝗪",X:"𝗫",Y:"𝗬",Z:"𝗭", 
        0:"𝟬",1:"𝟭",2:"𝟮",3:"𝟯",4:"𝟰",5:"𝟱",6:"𝟲",7:"𝟳",8:"𝟴",9:"𝟵",
        ñ:"𝗻̃",Ñ:"𝗡̃",á:"𝗮́",é:"𝗲́",í:"𝗶́",ó:"𝗼́",ú:"𝘂́",Á:"𝗔́",É:"𝗘́",Í:"𝗜́",Ó:"𝗢́",Ú:"𝗨́"
    },
    italic: { 
        a:"𝒶",b:"𝒷",c:"𝒸",d:"𝒹",e:"𝑒",f:"𝒻",g:"𝑔",h:"𝒽",i:"𝒾",j:"𝒿",k:"𝓀",l:"𝓁",m:"𝓂",n:"𝓃",o:"𝑜",p:"𝓅",q:"𝓆",r:"𝓇",s:"𝓈",t:"𝓉",u:"𝓊",v:"𝓋",w:"𝓌",x:"𝓍",y:"𝓎",z:"𝓏", 
        A:"𝒜",B:"𝐵",C:"𝒞",D:"𝒟",E:"𝐸",F:"𝐹",G:"𝒢",H:"𝐻",I:"𝐼",J:"𝒥",K:"𝒦",L:"𝐿",M:"𝑀",N:"𝒩",O:"𝒪",P:"𝒫",Q:"𝒬",R:"𝑅",S:"𝒮",T:"𝒯",U:"𝒰",V:"𝒱",W:"𝒲",X:"𝒳",Y:"𝒴",Z:"𝒵",
        0:"0",1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",
        ñ:"ñ",Ñ:"Ñ",á:"á",é:"é",í:"í",ó:"ó",ú:"ú",Á:"Á",É:"É",Í:"Í",Ó:"Ó",Ú:"Ú" // Nota: Italic nativo usa tildes estándar por diseño Unicode
    },
    monospace: {
        a:"𝚊",b:"𝚋",c:"𝚌",d:"𝚍",e:"𝚎",f:"𝚏",g:"𝚐",h:"𝚑",i:"𝚒",j:"𝚓",k:"𝚔",l:"𝚕",m:"𝚖",n:"𝚗",o:"𝚘",p:"𝚙",q:"𝚚",r:"𝚛",s:"𝚜",t:"𝚝",u:"𝚞",v:"𝚟",w:"𝚠",x:"𝚡",y:"𝚢",z:"𝚣",
        A:"𝙰",B:"𝙱",C:"𝙲",D:"𝙳",E:"𝙴",F:"𝙵",G:"𝙶",H:"𝙷",I:"𝙸",J:"𝙹",K:"𝙺",L:"𝙻",M:"𝙼",N:"𝙽",O:"𝙾",P:"𝙿",Q:"𝚀",R:"𝚁",S:"𝚂",T:"𝚃",U:"𝚄",V:"𝚅",W:"𝚆",X:"𝚇",Y:"𝚈",Z:"𝚉",
        0:"𝟶",1:"𝟷",2:"𝟸",3:"𝟹",4:"𝟺",5:"𝟻",6:"𝟼",7:"𝟽",8:"𝟾",9:"🟶",
        ñ:"𝚗̃",Ñ:"𝙽̃",á:"𝚊́",é:"𝚎́",í:"𝚒́",ó:"𝚘́",ú:"𝚞́",Á:"𝙰́",É:"𝙴́",Í:"𝙸́",Ó:"𝙾́",Ú:"𝚄́"
    },
    script: { 
        a:"𝓪",b:"𝓫",c:"𝓬",d:"𝓭",e:"𝓮",f:"𝓯",g:"𝓰",h:"𝓱",i:"𝓲",j:"𝓳",k:"𝓴",l:"𝓵",m:"𝓶",n:"𝓷",o:"𝓸",p:"𝓹",q:"𝓺",r:"𝓻",s:"𝓼",t:"𝓽",u:"𝓾",v:"𝓿",w:"𝔀",x:"𝔁",y:"𝔂",z:"𝔃", 
        A:"𝓐",B:"𝓑",C:"𝓒",D:"𝓓",E:"𝓔",F:"𝓕",G:"𝓖",H:"𝓗",I:"𝓘",J:"𝕵",K:"𝓚",L:"𝓛",M:"𝓜",N:"𝓝",O:"𝓞",P:"𝓟",Q:"𝓠",R:"𝓡",S:"𝓢",T:"𝓣",U:"𝓤",V:"𝓥",W:"𝓦",X:"𝓧",Y:"𝓨",Z:"𝓩",
        0:"𝟬",1:"𝟭",2:"𝟮",3:"𝟯",4:"𝟰",5:"𝟱",6:"𝟲",7:"𝟳",8:"𝟴",9:"𝟵",
        ñ:"𝓷̃",Ñ:"𝓝̃",á:"𝓪́",é:"𝓮́",í:"𝓲́",ó:"𝓸́",ú:"𝓾́",Á:"𝓐́",É:"𝓔́",Í:"𝓘́",Ó:"𝓞́",Ú:"𝓤́"
    }
};

// ==========================================
// 3. TRADUCTOR INVERSO (TU IDEA MAGISTRAL)
// ==========================================
function convertToNormal(text) {
    let normalText = "";
    
    // Convertimos el texto a un array para manejar caracteres Unicode complejos (como las fuentes estilizadas)
    const chars = [...text]; 
    
    for (let char of chars) {
        let found = false;
        
        // Buscamos a qué letra normal (a-z, A-Z, 0-9) pertenece ese carácter raro
        for (let style in fonts) {
            for (let normalChar in fonts[style]) {
                if (fonts[style][normalChar] === char) {
                    normalText += normalChar;
                    found = true;
                    break;
                }
            }
            if (found) break;
        }
        
        // Si no era una letra estilizada (ej. un espacio o un emoji), la dejamos igual
        if (!found) {
            normalText += char;
        }
    }
    return normalText;
}

// ==========================================
// 4. FUNCIONES CORE
// ==========================================

const updateCounter = () => {
    charCounter.textContent = `${[...composer.value].length} caracteres`;
};

const recordPos = () => {
    savedStart = composer.selectionStart;
    savedEnd = composer.selectionEnd;
};

composer.addEventListener('mouseup', recordPos);
composer.addEventListener('keyup', recordPos);
composer.addEventListener('focus', recordPos);

function transformSelection(style) {
    const text = composer.value;
    const selectedText = text.substring(savedStart, savedEnd);

    if (savedStart === savedEnd || !selectedText) {
        showToast("Selecciona el texto primero");
        return;
    }

    // 1. PRIMERO LIMPIAMOS EL TEXTO (Aplicando tu observación)
    const cleanText = convertToNormal(selectedText);

    // 2. AHORA SÍ LE APLICAMOS EL NUEVO ESTILO
    let transformed = "";
    if (style === "normal") {
        transformed = cleanText; // Si eligen "Fuente Estándar" se queda limpia
    } else {
        for (let char of cleanText) {
            transformed += (fonts[style] && fonts[style][char]) ? fonts[style][char] : char;
        }
    }

    // Reemplazo e inyección
    composer.value = text.substring(0, savedStart) + transformed + text.substring(end = savedEnd);
    
    composer.focus();
    composer.setSelectionRange(savedStart, savedStart + transformed.length);
    
    savedEnd = savedStart + transformed.length;
    updateCounter();
}

function addEmoji(char) {
    const text = composer.value;
    composer.value = text.substring(0, savedStart) + char + text.substring(savedEnd);
    const newPos = savedStart + char.length;
    composer.focus();
    composer.setSelectionRange(newPos, newPos);
    savedStart = savedEnd = newPos;
    updateCounter();
}

// ==========================================
// 5. EVENTOS DE INTERFAZ
// ==========================================
fontSelector.addEventListener('mousedown', recordPos);

fontSelector.onchange = function() {
    const estilo = this.value;
    transformSelection(estilo);
    
    setTimeout(() => {
        this.value = "normal";
        composer.focus();
    }, 10);
};

btnBold.onclick = (e) => { e.preventDefault(); recordPos(); transformSelection('bold'); };
btnItalic.onclick = (e) => { e.preventDefault(); recordPos(); transformSelection('italic'); };

document.getElementById('btnCopyAll').onclick = () => {
    composer.select();
    document.execCommand('copy');
    showToast("¡Copiado!");
};

document.getElementById('btnClear').onclick = () => {
    composer.value = "";
    savedStart = savedEnd = 0;
    updateCounter();
    composer.focus();
};

// ==========================================
// 6. EMOJIS (Renderizado)
// ==========================================
function renderEmojis(filter = "", category = "fuego") {
    grid.innerHTML = "";
    const filtered = emojiData.filter(item => 
        filter ? item.tags.toLowerCase().includes(filter.toLowerCase()) : item.cat === category
    );
    filtered.forEach(emoji => {
        const div = document.createElement('div');
        div.className = 'emoji-item';
        div.textContent = emoji.char;
        div.onclick = () => addEmoji(emoji.char);
        grid.appendChild(div);
    });
}

window.filterCategory = (cat, event) => {
    if (event) event.preventDefault();
    document.querySelectorAll('.category-nav button').forEach(b => b.classList.remove('active'));
    if (event) event.target.classList.add('active');
    renderEmojis("", cat);
};

function showToast(msg) {
    toast.textContent = msg;
    toast.classList.remove('hidden');
    setTimeout(() => toast.classList.add('hidden'), 2000);
}

searchInput.oninput = (e) => renderEmojis(e.target.value);
composer.oninput = updateCounter;

document.addEventListener('DOMContentLoaded', () => {
    renderEmojis("", "fuego");
    updateCounter();
});
